# This is a basic workflow to help you get started with Actions

name: Build Data

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  # Pausing the build on pull_request because it seems these cause a duplicate build which can fail.
  # I added this event because it seemed sometimes `push` was not causing a build.
  # So I'm leaving these comments until it's verified that `push` alone is good.
  #pull_request:
  #  types: [ closed ]
  #  branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:


    - name: Download
      run: wget --no-check-certificate 'https://drive.google.com/uc?export=download&confirm=abc&id=1-LA6lQ23rxrEHcrRMoWq6fMBKK9TtQtT' -O 'ratings.csv'
      
    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: main
        FOLDER: backend/data_files/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
